# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: JDK17_Maven_Run
    displayName: 'JDK17-Maven-Run'
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: JavaToolInstaller@0
        displayName: Install jdk
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Bash@3
        displayName: Run jdk11 maven
        inputs:
          targetType: 'inline'
          script: |
            ./mvnw clean package
  - job: JDK21_Maven_Run
    displayName: 'JDK21-Maven-Run'
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: JavaToolInstaller@0
        displayName: Install jdk
        inputs:
          versionSpec: '21'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Bash@3
        displayName: Run jdk21 maven
        inputs:
          targetType: 'inline'
          script: |
            ./mvnw clean package
  - job: JDK25_Maven_Run
    displayName: 'JDK25-Maven-Run'
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: JavaToolInstaller@0
        displayName: Install jdk
        inputs:
          versionSpec: '25'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Bash@3
        displayName: Run jdk25 maven
        inputs:
          targetType: 'inline'
          script: |
            ./mvnw clean package